os: linux
env:
  - arch: amd64
  - arch: arm
  - arch: i386

before_install:
  - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
  - sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
  - sudo apt-get update
  - sudo apt-get -y -o Dpkg::Options::="--force-confnew" install docker-ce

script:
  #- export arch=$(dpkg --print-architecture)
  #- if [[ $arch == arm* ]] ; then export arch=arm; fi
  - export DOCKER_CLI_EXPERIMENTAL=enabled
  - mkdir -p ~/.docker/cli-plugins
  - wget -q https://github.com/docker/buildx/releases/download/v0.3.1/buildx-v0.3.1.linux-amd64 -O ~/.docker/cli-plugins/docker-buildx
  - chmod a+x ~/.docker/cli-plugins/docker-buildx
  - sudo service docker stop
  - sudo dockerd --experimental &
  - echo "$DOCKERHUB_PASSWORD" | sudo docker login -u "$DOCKERHUB_USERNAME" --password-stdin
  #- sudo apt install -y -qq qemu qemu-user-static binfmt-support
  - sudo docker run --rm --privileged docker/binfmt:66f9012c56a8316f9244ffd7622d7c21c1f6f28d
  - sudo docker buildx create --name mybuilder
  - sudo docker buildx use mybuilder
  - sudo docker buildx inspect --bootstrap
  #- cd ${arch}/ && docker build . --platform ${arch} -t sagu/mariadb-alpine:${arch}
  - if [[ $arch == amd* ]] ; sudo docker buildx build --platform linux/amd64 -t sagu/mariadb-alpine:${arch} . --push; fi
  - if [[ $arch == arm* ]] ; sudo docker buildx build --platform linux/arm/v7 -t sagu/mariadb-alpine:${arch} . --push; fi
  - if [[ $arch == i38* ]] ; sudo docker buildx build --platform linux/386 -t sagu/mariadb-alpine:${arch} . --push; fi

jobs:
  include:
    - stage: deploy
      script:
        - export DOCKER_CLI_EXPERIMENTAL=enabled
        - sudo service docker stop
        - sudo dockerd --experimental &
        - echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
        - docker pull sagu/mariadb-alpine:amd64
        - docker pull sagu/mariadb-alpine:arm
        - docker manifest create sagu/mariadb-alpine:latest sagu/mariadb-alpine:amd64 sagu/mariadb-alpine:arm
        - docker manifest annotate sagu/mariadb-alpine:latest sagu/mariadb-alpine:amd64 --os linux --arch amd64
        - docker manifest annotate sagu/mariadb-alpine:latest sagu/mariadb-alpine:arm --os linux --arch arm
        - docker manifest annotate sagu/mariadb-alpine:latest sagu/mariadb-alpine:i386 --os linux --arch 386
        - docker manifest push sagu/mariadb-alpine:latest
