os: linux
#arch:
#  - amd64
#  - arm64
env:
  - arch: amd64
  - arch: arm

before_install:
  - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
  - sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
  - sudo apt-get update
  - sudo apt-get -y -o Dpkg::Options::="--force-confnew" install docker-ce

script:
  #- export arch=$(dpkg --print-architecture)
  #- if [[ $arch == arm* ]] ; then export arch=arm; fi
  - sudo mkdir -p ~/.docker/cli-plugins
  - wget -q https://github.com/docker/buildx/releases/download/v0.3.1/buildx-v0.3.1.linux-amd64 -O ~/.docker/cli-plugins/docker-buildx
  - sudo chmod a+x ~/.docker/cli-plugins/docker-buildx
  - sudo service docker stop
  - sudo dockerd --experimental &
  - sudo docker run --rm --privileged multiarch/qemu-user-static:register
  - sudo docker buildx create --name mybuilder
  - sudo docker buildx use mybuilder
  #- cd ${arch}/ && docker build . --platform ${arch} -t sagu/mariadb-alpine:${arch}
  - if [[ $arch == amd* ]] ; then cd ${arch}/ && sudo docker build . --platform ${arch} -t sagu/mariadb-alpine:${arch} ; fi
  - if [[ $arch == arm* ]] ; then cd ${arch}/ && sudo docker buildx build --platform linux/arm/v7 -t sagu/mariadb-alpine:${arch} . ; fi
  #- docker push sagu/mariadb-alpine:${arch}
  - echo "$DOCKERHUB_PASSWORD" | sudo docker login -u "$DOCKERHUB_USERNAME" --password-stdin && docker push sagu/mariadb-alpine:${arch}
  #- kill %1
  #- set +e
  #- pkill -9 -P $$ &> /dev/null || true
  #- exit 0

jobs:
  include:
    - stage: deploy
      script:
        - wget https://github.com/docker/buildx/releases/download/v0.3.1/buildx-v0.3.1.linux-amd64 -O ~/.docker/cli-plugins/docker-buildx
        - chmod a+x ~/.docker/cli-plugins/docker-buildx
        - sudo service docker stop
        - sudo dockerd --experimental &
        - echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
        - docker pull sagu/mariadb-alpine:amd64
        - docker pull sagu/mariadb-alpine:arm
        - docker manifest create sagu/mariadb-alpine:latest sagu/mariadb-alpine:amd64 sagu/mariadb-alpine:arm
        - docker manifest annotate sagu/mariadb-alpine:latest sagu/mariadb-alpine:amd64 --os linux --arch amd64
        - docker manifest annotate sagu/mariadb-alpine:latest sagu/mariadb-alpine:arm --os linux --arch arm
        - docker manifest push sagu/mariadb-alpine:latest