name: git

on:
  push:

jobs:
  git:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      # https://github.com/docker/setup-buildx-action#with-qemu
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
      - name: Available platforms
        run: echo ${{ steps.buildx.outputs.platforms }}
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: jubilee2
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Run Buildx arm
        run: |
          docker buildx build --platform linux/arm/v7 -t jubilee2/mariadb-alpine:arm . --push
      - name: Run Buildx 386
        run: |
          docker buildx build --platform linux/386 -t jubilee2/mariadb-alpine:386 . --push
      - name: Run Buildx amd64
        run: |
          docker buildx build --platform linux/amd64 -t jubilee2/mariadb-alpine:amd64 . --push
      - name: Latest
        run: |
          docker manifest create jubilee2/mariadb-alpine:latest jubilee2/mariadb-alpine:amd64 jubilee2/mariadb-alpine:arm jubilee2/mariadb-alpine:386
          docker manifest annotate jubilee2/mariadb-alpine:latest jubilee2/mariadb-alpine:amd64 --os linux --arch amd64
          docker manifest annotate jubilee2/mariadb-alpine:latest jubilee2/mariadb-alpine:arm --os linux --arch arm
          docker manifest annotate jubilee2/mariadb-alpine:latest jubilee2/mariadb-alpine:386 --os linux --arch 386
          docker manifest push jubilee2/mariadb-alpine:latest

